#!/bin/bash

createproblemfile() {
  local year=$1
  local day=$2
  local paddedDay=$(printf "%02d" $day)
  local type1=${3:-Any}
  local type2=${4:-Any}
  local package="dev.garlicbread.aoc"

  if [[ -z $year || -z $day ]]; then
    echo "Missing params."
    exit 1
  fi

  local problemdir="years/$year/src/dev/garlicbread/aoc/y$year/"
  if [[ ! -e "$problemdir" ]]; then
    mkdir -p "$problemdir"
    source tools/createmodulefile
    createModuleFile "$year"
  fi

  local file="${problemdir}Problem$paddedDay.kt"
  if [[ -e $file ]]; then
    read -p "File exists: ${file}. Overwrite? (y/N) " -r overwrite
    [[ "$overwrite" =~ ^[yY]$ ]] || return 0
  fi

  local name=$(curl -s https://adventofcode.com/$year/day/$day | awk '/--- Day [0-9]+: .* ---/ {
                         sub(/.*--- Day [0-9]+: /, "");
                         sub(/ ---.*/, "");
                         print $0
                     }')

  echo "Creating problem class: $file"
  echo "package $package.y$year

import ${package}.core.AocProblem
import ${package}.core.InputProvider
import ${package}.core.Problem
import ${package}.core.fileInputProvider
import ${package}.core.solve

fun main() = solve(
    benchmark = false,
) { Problem${paddedDay}() }

@AocProblem(year = $year, day = $day, name = \"$name\")
class Problem${paddedDay}(
    inputProvider: InputProvider = fileInputProvider<Problem$paddedDay>()
 ): Problem<${type1}, ${type2}>() {
    override val input = inputProvider.provideStringListInput()

    override fun solvePartOne(): ${type1} {
        return 0
    }

    override fun solvePartTwo(): ${type2} {
        return 0
    }
}" >"${file}"

  return $?
}