#!/bin/bash

createpuzzlefile() {
  local year=$1
  local day=$2
  local paddedDay=$(printf "%02d" $day)
  local type1=${3:-Any}
  local type2=${4:-Any}
  local package="dev.garlicbread.aoc"

  if [[ -z $year || -z $day ]]; then
    echo "Missing params."
    exit 1
  fi

  local puzzledir="years/$year/src/dev/garlicbread/aoc/y$year/"
  if [[ ! -e "$puzzledir" ]]; then
    mkdir -p "$puzzledir"
  fi

  local file="${puzzledir}Problem$paddedDay.kt"
  if [[ -e $file ]]; then
    read -p "File exists: ${file}. Overwrite? (y/N) " -r overwrite
    [[ "$overwrite" =~ ^[yY]$ ]] || return 0
  fi

  local name=$(curl -s https://adventofcode.com/$year/day/$day | awk '/--- Day [0-9]+: .* ---/ {
                         sub(/.*--- Day [0-9]+: /, "");
                         sub(/ ---.*/, "");
                         print $0
                     }')

  echo "Creating puzzle class: $file"
  echo "package $package.y$year

import ${package}.core.FileInputProvider
import ${package}.core.InputProvider
import ${package}.core.Puzzle
import ${package}.core.PuzzleMetadata
import ${package}.core.solve

fun main() = solve(
    benchmark = false,
) { Problem${paddedDay}() }

class Problem${paddedDay}(
    inputProvider: InputProvider = FileInputProvider(METADATA)
 ): Puzzle<${type1}, ${type2}>(
    metadata = METADATA,
) {
    override val input = inputProvider.provideStringListInput()

    override fun solvePartOne(): ${type1} {
        return 0
    }

    override fun solvePartTwo(): ${type2} {
        return 0
    }

    companion object {
        val METADATA = PuzzleMetadata(year = $year, day = $day, name = \"$name\")
    }
}" >"${file}"

  return $?
}