#!/bin/bash
createtestfile() {
  local year=$1
  local day=$2
  local paddedDay=$(printf "%02d" $day)
  local type1=${3:-Any}
  local type2=${4:-Any}

  if [[ -z $year || -z $day ]]; then
    echo "Missing params."
    exit 1
  fi

  local puzzledir="src/test/kotlin/dev/garlicbread/aoc/$year/"
  if [[ ! -e "$puzzledir" ]]; then
    mkdir "$puzzledir"
  fi

  local file="${puzzledir}Problem${paddedDay}Test.kt"
  if [[ -e $file ]]; then
    read -p "File exists: ${file}. Overwrite? (y/N) " -r overwrite
    [[ "$overwrite" =~ ^[yY]$ ]] || return 1
  fi

  echo "Creating test class: $file"
  echo "package dev.garlicbread.aoc.y${year}

import dev.garlicbread.aoc.PuzzleTest
import org.junit.jupiter.api.Test

internal class Problem${paddedDay}Test : PuzzleTest<${type1}, ${type2}>() {
    override val puzzle = { Problem${paddedDay}() }

    @Test
    fun problem${paddedDay}_1() {
        runTest(\"_1\", 0, 0)
    }
}" >"${file}"

  local inputfolder=src/test/resources/y$year/
  local inputfile="${inputfolder}input${day}_1.in"
  if [[ -e $inputfile ]]; then
    read -p "File exists: ${inputfile}. Overwrite? (y/N) " -r overwrite
    [[ "$overwrite" =~ ^[yY]$ ]] || return 1
  fi

  echo "Creating test input file: $inputfile"
  if [[ ! -d $inputfolder ]]; then
    mkdir "$inputfolder"
  fi
  touch "$inputfile"

  return $?
}